name = "CraftHub IV Modpack"
author = "ryenyuku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e65c5c2a5c419577278ada1a4c15e4e01839b5cd319bf9325539fbe1a6b8b0b6"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
